apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.99.111-192.168.99.122
      
# - name: ftps-ip
#   protocol: layer2
#   addresses:
#   - yyyy-yyyy
# - name: wordpress-ip
#   protocol: layer2
#   addresses:
#   - zzzz-zzzz